package nnsp.mappers;

import java.util.Map;

import org.apache.ibatis.annotations.Update;


public interface NcLogDateMapper {

	String CREATE_LOG_DATE = "CREATE TABLE nnet_cds2.nnc_log_access_#{table_name} ("
			+ "	`NLA_SEQ` INT(11) NOT NULL AUTO_INCREMENT,"
			+ "	`NLA_CREATE_DATE` DATETIME NULL DEFAULT NULL, "
			+ "	`NLA_HOST_NAME` VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf8_general_ci',"
			+ "	`NLA_RISK_LEVEL` CHAR(2) NULL DEFAULT NULL COLLATE 'utf8_general_ci', "
			+ "	`NLA_DIV` DECIMAL(2,0) NULL DEFAULT '1', "
			+ "	`NLA_SRC_IP` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8_general_ci', "
			+ "	`NLA_DST_IP` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8_general_ci', "
			+ "	`NLA_SRC_PORT` INT(11) NULL DEFAULT NULL, "
			+ "	`NLA_DST_PORT` INT(11) NULL DEFAULT NULL, "
			+ "	`NLA_PROTOCOL` INT(11) NULL DEFAULT NULL, "
			+ "	`NLA_ACCESS_TYPE` DECIMAL(2,0) NULL DEFAULT NULL, "
			+ "	PRIMARY KEY (`NLA_SEQ`) USING BTREE, "
			+ "	INDEX `nnc_log_access_idx1` (`NLA_CREATE_DATE`) USING BTREE ) "
			+ "COLLATE='utf8_general_ci' "
			+ "ENGINE=InnoDB";

	@Update(CREATE_LOG_DATE)
	int createTblLog(Map<String, Object> param);
	
	
	String CREATE_PACKET_TABLE = 
			" CREATE TABLE IF NOT EXISTS nnet_cds2.nnc_packet_stat_#{table_name} ( " + 
			" PS_ID BIGINT(20) NOT NULL AUTO_INCREMENT, " +  
			" PS_NIC_ID VARCHAR(32) NULL DEFAULT '', " +  
			" PS_STRC_TIME DATETIME NOT NULL, " +  
			" PS_PAYLOAD_SIZE INT(11) NULL DEFAULT 0, " +  
			" PS_TYPE VARCHAR(50) NULL DEFAULT '', " +  
			" PS_PROTO_ID VARCHAR(32) NULL DEFAULT '', " + 
			" PS_PROTO_SUB_TYPE VARCHAR(32) NULL DEFAULT '', " + 
			" PS_PROTO_SUB_DEC VARCHAR(32) NULL DEFAULT '', " + 
			" PS_PROTO_ICS INT(11) NULL DEFAULT 0, " + 
			" PS_PROTO_ICS_TYPE INT(11) NULL DEFAULT 0, " + 
			" PS_PROTO_ICS_CMD_TYPE INT(11) NULL DEFAULT 0, " +  
			" PS_SRC_MAC VARCHAR(17) NULL DEFAULT '', " + 
			" PS_SRC_MAC_VENDOR VARCHAR(128) NULL DEFAULT '', " +  
			" PS_SRC_ICS_VENDOR INT(11) NULL DEFAULT 0, " + 
			" PS_SRC_ICS_Layer INT(11) NULL DEFAULT 0, " + 
			" PS_DST_MAC VARCHAR(17) NULL DEFAULT '', " + 
			" PS_DST_MAC_VENDOR VARCHAR(128) NULL DEFAULT '', " +  
			" PS_DST_ICS_VENDOR INT(11) NULL DEFAULT 0, " + 
			" PS_DST_ICS_Layer INT(11) NULL DEFAULT 0, " + 
			" PS_ETHER_TYPE VARCHAR(24) NULL DEFAULT '', " + 
			" PS_ETHER_TYPE_DEC VARCHAR(128) NULL DEFAULT '', " + 
			" PS_DSAP VARCHAR(50) NULL DEFAULT '', " + 
			" PS_SSAP VARCHAR(50) NULL DEFAULT '', " + 
			" PS_ORGANIZATION VARCHAR(50) NULL DEFAULT '', " + 
			" PS_PID VARCHAR(50) NULL DEFAULT '', " + 
			" PS_SRC_IP VARCHAR(15) NULL DEFAULT '', " + 
			" PS_DST_IP VARCHAR(15) NULL DEFAULT '', " + 
			" PS_SRC_IP_INT BIGINT(20) NULL DEFAULT 0, " + 
			" PS_DST_IP_INT BIGINT(20) NULL DEFAULT 0, " + 
			" PS_SRC_PORT INT(11) NULL DEFAULT 0, " + 
			" PS_DST_PORT INT(11) NULL DEFAULT 0, " + 
			" PS_TCP_FLAG VARCHAR(8) NULL DEFAULT '', " + 
			" PS_TCP_FLAG_DEC VARCHAR(32) NULL DEFAULT '', " + 
			" PS_ICS_HEADER1 VARCHAR(64) NULL DEFAULT '', " + 
			" PS_ICS_HEADER2 VARCHAR(64) NULL DEFAULT '', " + 
			" PS_ICS_HEADER3 VARCHAR(64) NULL DEFAULT '', " + 
			" PS_ICS_HEADER4 VARCHAR(64) NULL DEFAULT '', " + 
			" PS_ICS_HEADER5 VARCHAR(64) NULL DEFAULT '', " + 
			" PS_ICS_HEADER6 VARCHAR(64) NULL DEFAULT '', " + 
			" PS_ICS_HEADER7 VARCHAR(64) NULL DEFAULT '', " + 
			" PS_ICS_HEADER8 VARCHAR(64) NULL DEFAULT '', " + 
			" PS_ICS_HEADER9 VARCHAR(64) NULL DEFAULT '', " + 
			" PS_ICS_HEADER10 VARCHAR(64) NULL DEFAULT '', " + 
			" PS_ICS_HEADER11 VARCHAR(64) NULL DEFAULT '', " + 
			" PS_ICS_HEADER12 VARCHAR(64) NULL DEFAULT '', " + 
			" PS_ICS_HEADER13 VARCHAR(64) NULL DEFAULT '', " + 
			" PS_ICS_HEADER14 VARCHAR(64) NULL DEFAULT '', " + 
			" PS_WHITE_RULE VARCHAR(260) NULL DEFAULT '', " + 
			" PS_WHITE_RESULT INT(11) NULL DEFAULT 0, " + 
			" PS_FLOW_RESULT INT(11) NULL DEFAULT 0, " + 
			" PS_FLOW_VALUE INT(11) NULL DEFAULT 0, " + 
			" PS_PACKETS BIGINT(20) NULL DEFAULT 0, " + 
			" PS_BYTES BIGINT(20) NULL DEFAULT 0, " + 
			" PS_REGDTTM DATETIME NULL DEFAULT now(), " + 
			" PS_INOUT INT(11) NULL DEFAULT '0' COMMENT 'Outbound(0)/Inbound(1)   구분', " + 
			" PS_DETECT INT(11) NULL DEFAULT '0' COMMENT '접근제어 허용(1)/차단(0)/악성코드 탐지(2)', " + 
			" PS_DETECT_DESC TEXT NULL DEFAULT '' COMMENT '접근제어 탐지 내용', " + 
			" WL_ID BIGINT(20) NULL DEFAULT '0' COMMENT '정책 ID', " + 
			" PRIMARY KEY (PS_ID), " + 
			" INDEX PS_STRC_TIME (PS_STRC_TIME), " + 
			" INDEX PS_PROTO_SUB_DEC (PS_PROTO_SUB_DEC), " + 
			" INDEX PS_SRC_IP (PS_SRC_IP), " + 
			" INDEX PS_DST_IP (PS_DST_IP), " + 
			" INDEX PS_WHITE_RULE (PS_WHITE_RULE), " + 
			" INDEX PS_INOUT (PS_INOUT), " + 
			" INDEX WL_ID (WL_ID) " + 
			" )COLLATE='utf8_general_ci' " + 
			" ENGINE=InnoDB ";
	
	@Update(CREATE_PACKET_TABLE)
	int createTblPacket(Map<String, Object> param);
}